### ISSUE TITLE
分流无效

### ISSUE THREAD

**Issue by Wyatt323** [wgetnz/chatgpt-openclash#1]
我将您的配置文件修改成chatgpt可以手动选择节点，但是实际使用的时候并没有生效（chatgpt选择的可以上chatgpt的节点，其他的都是走一个不能访问的节点），最后还是出现了Access denied，ip是哪个不能访问的节点的ip

![image](https://user-images.githubusercontent.com/71224625/222726464-848eee32-b4e8-4c0f-af79-a150ca62362c.png)

**Comment by wgetnz** [comment]
需清空浏览器数据，或者你在无恒模式下测试

**Comment by Wyatt323** [comment]
刚才试了一下，必须开tun模式才生效，感谢大佬

**Comment by wgetnz** [comment]
> 刚才试了一下，必须开tun模式才生效，感谢大佬

我之前在fake-ip模式下有域名解析错误，fake-IP应该不行，默认Redir-Host 兼容模式是OK的

**Comment by wgetnz** [comment]
readme已更新相关细节，请参考最新readme

**Comment by Wyatt323** [comment]
> > 刚才试了一下，必须开tun模式才生效，感谢大佬
> 
> 我之前在fake-ip模式下有域名解析错误，fake-IP应该不行，默认Redir-Host 兼容模式是OK的


好奇怪，我在Redir-Host 兼容模式不行诶，上午说开了tun可以用了，但是有影响我游戏搜服务器了

**Comment by wgetnz** [comment]
已修复
