### ISSUE TITLE
配置无法更新

### ISSUE THREAD

**Issue by foreverDC** [wgetnz/chatgpt-openclash#3]
ruleset=🎯 Chatgpt,https://raw.githubusercontent.com/wgetnz/chatgpt/main/chatgpt.list
custom_proxy_group=🎯 chatgpt`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
第一处和第二处chatgpt大小写不一致，两处一致后可以正常更新订阅，否则会报错：
FTL [Config] parse config failed error=rules[3] [DOMAIN-SUFFIX,openai.com,🎯 Chatgpt] error: proxy [🎯 Chatgpt] not found

**Comment by wgetnz** [comment]
已更新，感谢，可再次尝试

**Comment by wgetnz** [comment]
已修复
