### ISSUE TITLE
你好，请问clash for windows如何使用？

### ISSUE THREAD

**Issue by wcribug** [wgetnz/chatgpt-openclash#5]
使用clash for windows按照同样方法操作以后得到的配置文件里面没有节点，请问是因为什么呢？

**Comment by wgetnz** [comment]
检查订阅地址是否可联

**Comment by wcribug** [comment]
您好，订阅地址是没问题的，可以更新订阅。将订阅地址替换到您给的链接中会下载到一个规则完备但节点为空的配置文件。
![image](https://user-images.githubusercontent.com/62501687/232232287-954325e9-9b4a-4a20-9d2a-02242f5e7031.png)

**Comment by wgetnz** [comment]
可以将订阅地址使用gpg加密后发我，我排查下

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZDrJVxYJKwYBBAHaRw8BAQdAqBo25Gje9DTtPINXdx8a1h9uR2Vohm1Dz95Y
J8GJEdi0BnB1YmxpY4iZBBMWCgBBFiEEWvhnTw61p/7vC1KC3aRxHuXzUw0FAmQ6
yVcCGyMFCQ6BKWkFCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQ3aRxHuXz
Uw2VCQEAlvOW0KgGCzduqDvbafBrmf3z1La8l/hLXbVCBRHe4qMA/0bFHhcTSV8W
nb8+LAZkmdTTH5o+DSNiPyWg9DydD3kBuDgEZDrJVxIKKwYBBAGXVQEFAQEHQCCA
JrshNoNim+/Uf16XJWoOEiqu31TjEE2Zw+5yl4xsAwEIB4h+BBgWCgAmFiEEWvhn
Tw61p/7vC1KC3aRxHuXzUw0FAmQ6yVcCGwwFCQ6BKWkACgkQ3aRxHuXzUw0p+QEA
kG10Y2sboxVR6nop0IXvAYcQxN/a+JXx/QHwl9d/S0YBAK+CJcszsl4Yshkv0N88
IOv7jKt95yd1EiuXbnYDxgoP
=EnJE
-----END PGP PUBLIC KEY BLOCK-----

**Comment by wgetnz** [comment]
经过排查，发现可能是订阅连接没使用URL编码，导致获取不到节点信息
https://api.dler.io/sub?target=clash&new_name=true&url=你的订阅链接(需要使用URL编码，)&config=https%3A%2F%2Fraw.githubusercontent.com%2Fwgetnz%2Fchatgpt%2Fmain%2FFull.ini

http://www.jsons.cn/urlencode/  使用编码后的地址替换即可
![2023-04-16_01-12-14](https://user-images.githubusercontent.com/62410571/232241938-8e25ba1c-cd30-4389-9ca5-96b226558702.png)

**Comment by wcribug** [comment]
感谢！按照您的方法已经成功了
